# Generated by Django 5.1.3 on 2026-03-29 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilatesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=10)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilates Class',
                'verbose_name_plural': 'Pilates Classes',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('pilates_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.pilatesclass')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pilatesclass',
            index=models.Index(fields=['date', 'start_time'], name='scheduling__date_e97431_idx'),
        ),
        migrations.AddIndex(
            model_name='pilatesclass',
            index=models.Index(fields=['instructor'], name='scheduling__instruc_0ab9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='scheduling__user_id_2ca7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pilates_class', 'status'], name='scheduling__pilates_366fcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'pilates_class')},
        ),
    ]
